### ISSUE TITLE
Sign up/ Register page

### ISSUE THREAD

**Issue by firebase007** [acekyd/devcomm#34]
Issues with signing up. The text fields were consistently misbehaving

**Comment by biodunch** [comment]
What was the misbehaviour ¿ :-)

**Comment by firebase007** [comment]
I wasn't able to sign up. When I click on the text field for email,the already filled out name field clears out. Just a little twirks here and there

**Comment by biodunch** [comment]
Ah, I see... What browser ¿

**Comment by firebase007** [comment]
On my mobile device. Mobile browser(chrome)

**Comment by acekyd** [comment]
Hello @firebase007 please provide more insight. I have been unable to replicate this issue. Have you tried again or on another browser?

**Comment by firebase007** [comment]
Hello @acekyd. It is working perfectly well now. I tried it again on the same browser. Thanks
