### ISSUE TITLE
Incomprehensible codebase.

### ISSUE THREAD

**Issue by uncle-tee** [acekyd/devcomm#58]
Nice one, one the other hand am trying to contribute to this project as open source is the new source. On the other hand the controllers are returning Json. Without any views. However the web resource has only two routes. Please do a summary code review so I can kick off.

**Comment by acekyd** [comment]
Hello... The project uses React for the front end. Which is why the controllers are returning JSON. I'll add more information to the readme to make this easily understandable. Thanks.
